{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1a7ad55e-4c95-4f78-917d-5eb70ba66839",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!pip install \"ray[default]\" --user\n",
    "#!pip install install \"ray[serve]\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "74750075-9142-441c-ac6d-2496b04b2922",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n"
     ]
    },
    {
     "ename": "Exception",
     "evalue": "Trying to start two instances of ray via client",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mException\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-21-cc3cea93bf8e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m    \u001b[0mservice_host\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0menviron\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"RAY_HEAD_SERVICE_HOST\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     44\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     45\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mclient_mode_should_convert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 46\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mray\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     47\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     48\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/ray/util/client/__init__.py\u001b[0m in \u001b[0;36minit\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    130\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0minit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    131\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_server\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 132\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trying to start two instances of ray via client\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    133\u001b[0m         \u001b[0;32mimport\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutil\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mserver\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mserver\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mray_client_server\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    134\u001b[0m         server_handle, address_info = ray_client_server.init_and_serve(\n",
      "\u001b[0;31mException\u001b[0m: Trying to start two instances of ray via client"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-10-11 17:57:54,834\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:57:56,280\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:57:57,727\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:57:59,164\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:00,621\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:02,068\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:03,513\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:04,948\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:06,393\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:07,837\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:09,285\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:10,719\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:12,176\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:13,612\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:15,057\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:16,503\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:17,941\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:19,389\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:20,826\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:22,275\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:23,710\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:25,148\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "2021-10-11 17:58:26,616\tWARNING worker.py:1115 -- The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "The agent on node run-616472e9e1bdfe705350cd8d-jsk6j failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "    self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "    return await aioredis.create_redis_pool(\n",
      "AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 338, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 326, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/opt/conda/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/agent.py\", line 121, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.aioredis_client = await dashboard_utils.get_aioredis_client(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/ubuntu/.local/lib/python3.8/site-packages/ray/new_dashboard/utils.py\", line 662, in get_aioredis_client\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return await aioredis.create_redis_pool(\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m AttributeError: module 'aioredis' has no attribute 'create_redis_pool'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Error processing line 3 of /opt/conda/lib/python3.8/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"/opt/conda/lib/python3.8/site.py\", line 169, in addpackage\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m       exec(line)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<string>\", line 1, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     File \"<frozen importlib._bootstrap>\", line 553, in module_from_spec\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   AttributeError: 'NoneType' object has no attribute 'loader'\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m \n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Remainder of file ignored\n"
     ]
    }
   ],
   "source": [
    "import ray\n",
    "import os\n",
    "ray.init(\"ray://\"+os.environ[\"RAY_HEAD_SERVICE_HOST\"]\":\"+os.environ[\"RAY_HEAD_SERVICE_PORT\"])\n",
    "if ray.is_initialized() == False:\n",
    "   service_host = os.environ[\"RAY_HEAD_SERVICE_HOST\"]\n",
    "   service_port = os.environ[\"RAY_HEAD_SERVICE_PORT\"]\n",
    "   ray.util.connect(f\"{service_host}:{service_port}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c81a995a-cde1-4d13-ae60-2754822723fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "if ray.is_initialized() == False:\n",
    "   service_host = os.environ[\"RAY_HEAD_SERVICE_HOST\"]\n",
    "   service_port = os.environ[\"RAY_HEAD_SERVICE_PORT\"]\n",
    "   ray.util.connect(f\"{service_host}:{service_port}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "57ee6df7-cb98-4964-bd72-4e1775a88716",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import requests\n",
    "from ray import serve\n",
    "\n",
    "@serve.deployment\n",
    "def hello(request):\n",
    "    name = request.query_params[\"name\"]\n",
    "    return f\"Hello {name}!\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6a86be95-af0f-4fdc-8149-911bd524220c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#ray.serve.init(name=\"ModelServing\", http_host=service_host, http_port=8800)\n",
    "\n",
    "serve.start(http_port=8800)\n",
    "hello.deploy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dfaabac2-4240-42f4-a4a6-ad06b694c761",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Query our endpoint over HTTP.\n",
    "endpoint = \"http://\" + service_host + \":8000/hello?name=serve\"\n",
    "#endpoint = \"http://\" + \"127.0.0.1:8000/hello?name=serve\"\n",
    "response = requests.get(endpoint).text\n",
    "print(response)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ebf3f0b2-0347-4d61-97d6-8894624c8e91",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
